from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from .money import parse_ap

AP = "ap"
SHADOW_AP = "shadow_ap"
SINGULARITY_SHARD = "singularity_shard"
NEURAL_SHARD = "neural_shard"


@dataclass(frozen=True)
class ShopItem:
    key: str
    title: str
    section: str
    currency: str = AP
    base_cost: Decimal = Decimal("0.000")
    cost_formula: str = "fixed"
    max_level: int | None = None
    discount_tags: tuple[str, ...] = ()
    gate: str = ""
    effect_kind: str = "manual"
    description: str = ""


def ap(value: str) -> Decimal:
    return parse_ap(value)


SHOP_ITEMS: tuple[ShopItem, ...] = (
    ShopItem(
        "terminal.core",
        "Ядро Вычислений",
        "terminal",
        base_cost=ap("0"),
        cost_formula="core",
        discount_tags=("terminal", "core"),
        effect_kind="core_upgrade",
        description="Прокачка базовой ставки. Цена: текущая база x10.",
    ),
    ShopItem(
        "terminal.vector",
        "Векторная Специализация",
        "terminal",
        base_cost=ap("0"),
        cost_formula="vector",
        discount_tags=("terminal", "vector"),
        effect_kind="vector_upgrade",
        description="Прокачка выбранного рабочего вектора на +10%.",
    ),
    ShopItem(
        "terminal.cashback",
        "Кэшбек-Шина Терминала",
        "terminal",
        base_cost=ap("3"),
        cost_formula="cashback",
        max_level=5,
        effect_kind="cashback_upgrade",
        description="5% возврата/скидки за уровень, цена уровня 3+i AP.",
    ),
    ShopItem(
        "terminal.retro_buffer",
        "Ретро-Буфер",
        "terminal",
        base_cost=ap("0"),
        cost_formula="retro_buffer",
        effect_kind="retro_buffer",
        description="Одноразовый перерасчет последних задач с динамической комиссией.",
    ),
    ShopItem(
        "hub.scanning",
        "Модуль Расширенного Сканирования",
        "hub",
        base_cost=ap("10"),
        cost_formula="linear_level",
        effect_kind="level",
    ),
    ShopItem(
        "hub.intel",
        "Модуль Расширенного Сведения",
        "hub",
        base_cost=ap("10"),
        cost_formula="linear_level",
        effect_kind="level",
    ),
    ShopItem(
        "hub.genre_focus",
        "Фокус Жанра",
        "hub",
        base_cost=ap("5"),
        cost_formula="linear_level",
        discount_tags=("hub", "genre"),
        effect_kind="level",
    ),
    ShopItem(
        "hub.extractor",
        "Транс-Пространственный Извлекатель",
        "hub",
        base_cost=ap("0.5"),
        cost_formula="linear_level",
        discount_tags=("hub", "extractor"),
        effect_kind="level",
    ),
    ShopItem(
        "hub.attribute",
        "Генетический и Информационный Код",
        "hub",
        base_cost=ap("0.1"),
        cost_formula="attribute",
        max_level=200,
        discount_tags=("hub", "attribute"),
        effect_kind="level",
    ),
    ShopItem(
        "hub.luck",
        "Удача",
        "hub",
        base_cost=ap("1"),
        cost_formula="linear_level",
        max_level=1000,
        discount_tags=("hub", "attribute"),
        effect_kind="level",
    ),
    ShopItem(
        "hub.erudition",
        "Адаптивная Эрудиция",
        "hub",
        base_cost=ap("0.1"),
        cost_formula="attribute",
        max_level=200,
        discount_tags=("hub", "erudition"),
        effect_kind="level",
    ),
    ShopItem(
        "hub.optimization",
        "Алгоритмы Оптимизации",
        "hub",
        base_cost=ap("1"),
        cost_formula="linear_level",
        max_level=90,
        effect_kind="target_discount",
    ),
    ShopItem(
        "hub.living_block",
        "Расширение Жилого Блока",
        "hub",
        base_cost=ap("1"),
        cost_formula="linear_level",
        effect_kind="level",
    ),
    ShopItem(
        "hub.conflict_isolation",
        "Протокол: Изоляция Конфликтов",
        "hub",
        base_cost=ap("5"),
        cost_formula="linear_level",
        effect_kind="level",
    ),
    ShopItem(
        "hub.sync_protocol",
        "Протокол: Синхронизация",
        "hub",
        base_cost=ap("10"),
        cost_formula="fixed",
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.reroll",
        "Рекалибровка",
        "expedition",
        base_cost=ap("0.5"),
        cost_formula="fixed",
        discount_tags=("expedition", "search"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.abstraction",
        "Понижение Абстракции",
        "expedition",
        base_cost=ap("1"),
        cost_formula="fixed",
        discount_tags=("expedition", "search"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.intel",
        "Разведка Персоналий",
        "expedition",
        base_cost=ap("1"),
        cost_formula="fixed",
        discount_tags=("expedition", "intel"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.chrono_pointer",
        "Хроно-указатель",
        "expedition",
        base_cost=ap("1"),
        cost_formula="target_number",
        discount_tags=("expedition", "boss"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.avatar_trait",
        "Кастомизация Аватара",
        "expedition",
        base_cost=ap("0.2"),
        cost_formula="quantity",
        discount_tags=("expedition", "avatar"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.target_request",
        "Целевой Запрос",
        "expedition",
        base_cost=ap("3"),
        cost_formula="fixed",
        discount_tags=("expedition", "route"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.ng",
        "Новая Игра",
        "expedition",
        base_cost=ap("1"),
        cost_formula="fixed",
        discount_tags=("expedition", "route"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.ng_plus",
        "Новая Игра Плюс",
        "expedition",
        base_cost=ap("2"),
        cost_formula="fixed",
        discount_tags=("expedition", "route"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.hijack",
        "Захват Чужой Симуляции",
        "expedition",
        base_cost=ap("3"),
        cost_formula="fixed",
        discount_tags=("expedition", "route"),
        effect_kind="manual",
    ),
    ShopItem(
        "expedition.isolated_singularity",
        "Изолированная Сингулярность",
        "expedition",
        base_cost=ap("10"),
        cost_formula="quantity",
        discount_tags=("expedition", "premium"),
        effect_kind="manual",
        description="10 AP за неделю.",
    ),
    ShopItem(
        "world.rollback",
        "Локальный Реверс Хронологии",
        "world",
        base_cost=ap("0"),
        cost_formula="rollback",
        discount_tags=("world", "rollback"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.adaptation",
        "Адаптация",
        "world",
        base_cost=ap("1"),
        cost_formula="fixed",
        discount_tags=("world", "ability"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.prerequisite",
        "Интеграция Пререквизитов",
        "world",
        base_cost=ap("1"),
        cost_formula="quantity",
        discount_tags=("world", "ability"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.rental",
        "Протокол Аренды",
        "world",
        base_cost=ap("1"),
        cost_formula="rental",
        discount_tags=("world", "ability"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.infiltrator",
        "Когнитивный Инфильтратор",
        "world",
        base_cost=ap("0.5"),
        cost_formula="infiltrator",
        discount_tags=("world", "infiltrator"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.skip",
        "Быстрое Перемещение",
        "world",
        base_cost=ap("1"),
        cost_formula="skip",
        discount_tags=("world", "skip"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.perfect_algorithm",
        "Идеальный Алгоритм",
        "world",
        base_cost=ap("0"),
        cost_formula="perfect_algorithm",
        discount_tags=("world", "skip"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.cache_unfreeze",
        "Разморозка мира",
        "world",
        base_cost=ap("1"),
        cost_formula="fixed",
        discount_tags=("world", "cache"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.cache_clear_current",
        "Очистка мира из текущего пула",
        "world",
        base_cost=ap("1"),
        cost_formula="fixed",
        discount_tags=("world", "cache"),
        effect_kind="manual",
    ),
    ShopItem(
        "world.cache_clear_forever",
        "Удалить мир навсегда",
        "world",
        base_cost=ap("2"),
        cost_formula="fixed",
        discount_tags=("world", "cache"),
        effect_kind="manual",
    ),
    ShopItem(
        "recreation.memory_snapshot",
        "Снимок Памяти",
        "recreation",
        base_cost=ap("0.2"),
        cost_formula="quantity",
        discount_tags=("recreation", "visual"),
        effect_kind="manual",
    ),
    ShopItem(
        "recreation.gacha",
        "Дешифровка Случайного Архива",
        "recreation",
        base_cost=ap("0.2"),
        cost_formula="quantity",
        discount_tags=("recreation", "gacha"),
        effect_kind="gacha",
    ),
    ShopItem(
        "recreation.nsfw",
        "Снятие Цензуры",
        "recreation",
        base_cost=ap("0.3"),
        cost_formula="quantity",
        discount_tags=("recreation", "visual"),
        effect_kind="manual",
    ),
    ShopItem(
        "genesis.recombination",
        "Рекомбинация",
        "genesis",
        base_cost=ap("1"),
        cost_formula="fixed",
        discount_tags=("genesis",),
        effect_kind="manual",
    ),
    ShopItem(
        "genesis.splice",
        "Точечное Сращивание",
        "genesis",
        base_cost=ap("2"),
        cost_formula="fixed",
        discount_tags=("genesis",),
        effect_kind="manual",
    ),
    ShopItem(
        "genesis.marker_lock",
        "Фиксация Маркера",
        "genesis",
        base_cost=ap("1"),
        cost_formula="fixed",
        discount_tags=("genesis",),
        effect_kind="manual",
    ),
    ShopItem(
        "genesis.gene_evolution",
        "Генная Эволюция",
        "genesis",
        base_cost=ap("3"),
        cost_formula="fixed",
        discount_tags=("genesis",),
        effect_kind="manual",
    ),
    ShopItem(
        "genesis.defect_excision",
        "Иссечение Дефекта",
        "genesis",
        base_cost=ap("10"),
        cost_formula="fixed",
        discount_tags=("genesis",),
        effect_kind="manual",
    ),
    ShopItem(
        "prime.subscription",
        "ASSIR PRIME",
        "prime",
        base_cost=ap("10"),
        cost_formula="prime",
        effect_kind="prime_extend",
        description="10 AP за неделю, с прогрессивной скидкой до 6 AP.",
    ),
    ShopItem(
        "prime.cryo_stasis",
        "Крио-Стазис PRIME",
        "prime",
        base_cost=ap("1"),
        cost_formula="fixed",
        effect_kind="prime_stasis",
    ),
    ShopItem(
        "noctur.autonomy",
        "Архитектура Автономии",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("1"),
        cost_formula="shard_linear",
        max_level=3,
        gate="noctur",
        effect_kind="level",
    ),
    ShopItem(
        "noctur.core_rewrite",
        "Перезапись Ядра Вычислений",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("4"),
        cost_formula="shard_linear",
        max_level=3,
        gate="noctur",
        effect_kind="level",
    ),
    ShopItem(
        "noctur.limiter_removal",
        "Снятие Ограничителей",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("2"),
        cost_formula="shard_linear",
        max_level=3,
        gate="noctur",
        effect_kind="level",
    ),
    ShopItem(
        "noctur.cascade",
        "Каскадный Резонанс",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("3"),
        cost_formula="cascade",
        max_level=2,
        gate="noctur",
        effect_kind="level",
    ),
    ShopItem(
        "noctur.absolute_limit",
        "Абсолютный Предел",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("1"),
        cost_formula="shard_linear",
        max_level=10,
        gate="noctur",
        effect_kind="level",
    ),
    ShopItem(
        "noctur.author_right",
        "Право Автора",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("5"),
        cost_formula="fixed",
        gate="noctur",
        effect_kind="manual",
    ),
    ShopItem(
        "noctur.echo_projection",
        "Проекция Эхо-Материи",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("4"),
        cost_formula="shard_linear",
        max_level=3,
        gate="noctur",
        effect_kind="level",
    ),
    ShopItem(
        "noctur.overclock",
        "Агрессивный Разгон",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("3"),
        cost_formula="fixed",
        gate="noctur",
        effect_kind="overclock_unlock",
    ),
    ShopItem(
        "noctur.quantum_archive",
        "Квантовая Архивизация",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("2"),
        cost_formula="shard_linear",
        max_level=3,
        gate="noctur",
        effect_kind="level",
    ),
    ShopItem(
        "noctur.tax_bypass",
        "Обход Налогообложения",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("3"),
        cost_formula="shard_linear",
        max_level=3,
        gate="noctur",
        effect_kind="level",
    ),
    ShopItem(
        "noctur.shadow_investment",
        "Теневые Инвестиции",
        "noctur",
        currency=SINGULARITY_SHARD,
        base_cost=ap("4"),
        cost_formula="fixed",
        gate="noctur",
        effect_kind="level",
    ),
)

SHOP_BY_KEY = {item.key: item for item in SHOP_ITEMS}


def require_shop_item(key: str) -> ShopItem:
    try:
        return SHOP_BY_KEY[key]
    except KeyError as exc:
        raise KeyError(f"Shop item not found: {key}") from exc
